# Generated by Django 4.2 on 2023-04-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_no', models.IntegerField(primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('mentor', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('student_father_name', models.CharField(max_length=50)),
                ('student_mother_name', models.CharField(max_length=50)),
                ('Address', models.TextField(max_length=100)),
            ],
        ),
    ]
