# Generated by Django 4.2 on 2023-04-11 09:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=phone_field.models.PhoneField(max_length=31),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
